version: '3.5'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/local/nginx/:/etc/nginx/conf.d/
            - ./:/var/www/
        ports:
            - "8001:80"
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: docker/local/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: app
        depends_on:
            - db

    db:
      image: postgres:15
      volumes:
        - ./tmp/db:/var/lib/postgresql/
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_DB=robin
        - POSTGRES_PASSWORD=root
      container_name: db

    redis:
      image: redis:latest
      volumes:
        - ./redis/data/:/data
      ports:
        - "6379:6379"
      container_name: redis
      links:
        - nginx
